name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Run linter
        run: task lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Install age-keygen for integration tests
        run: go install filippo.io/age/cmd/age-keygen@latest
      - name: Run tests
        run: task test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Build
        run: task build